import { useEffect, useMemo, useState } from "react";
import { Navigate, Link } from "react-router-dom";
import { Loader2, Search, Download, ArrowLeft } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/context/AuthContext";
import { useIsAdmin } from "@/hooks/useIsAdmin";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";

interface WorksheetRow {
  id: string;
  query: string;
  file_path: string | null;
  created_at: string;
  user_id: string | null;
  display_name: string | null;
}

const PAGE = 1000;

const truncate = (s: string, n: number) => (s.length > n ? `${s.slice(0, n)}…` : s);
const formatDate = (iso: string) =>
  new Date(iso).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

const AdminWorksheets = () => {
  const { authLoading } = useAuth();
  const { isAdmin, loading: adminLoading } = useIsAdmin();

  const [rows, setRows] = useState<WorksheetRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  useEffect(() => {
    if (!isAdmin) return;
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        // Paginate worksheet_downloads
        const all: Array<{ id: string; query: string; file_path: string | null; created_at: string; user_id: string | null }> = [];
        for (let from = 0; ; from += PAGE) {
          const { data, error } = await supabase
            .from("worksheet_downloads")
            .select("id, query, file_path, created_at, user_id")
            .order("created_at", { ascending: false })
            .range(from, from + PAGE - 1);
          if (error) throw error;
          if (!data || data.length === 0) break;
          all.push(...data);
          if (data.length < PAGE) break;
        }

        // Fetch matching user_profiles
        const userIds = Array.from(new Set(all.map((r) => r.user_id).filter(Boolean) as string[]));
        const nameMap = new Map<string, string>();
        if (userIds.length > 0) {
          const { data: profiles, error: pErr } = await supabase
            .from("user_profiles")
            .select("id, display_name")
            .in("id", userIds);
          if (pErr) throw pErr;
          (profiles ?? []).forEach((p) => {
            if (p.display_name) nameMap.set(p.id, p.display_name);
          });
        }

        if (cancelled) return;
        setRows(all.map((r) => ({ ...r, display_name: r.user_id ? nameMap.get(r.user_id) ?? null : null })));
      } catch (err) {
        console.error(err);
        toast.error("Failed to load worksheets");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [isAdmin]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return rows;
    return rows.filter((r) => r.query.toLowerCase().includes(q));
  }, [rows, search]);

  const handleDownload = async (row: WorksheetRow) => {
    if (!row.file_path) return;
    setDownloadingId(row.id);
    try {
      const { data, error } = await supabase.storage
        .from("worksheets")
        .createSignedUrl(row.file_path, 3600);
      if (error || !data?.signedUrl) throw error ?? new Error("No URL");
      window.open(data.signedUrl, "_blank", "noopener,noreferrer");
    } catch (err) {
      console.error(err);
      toast.error("Could not generate download link");
    } finally {
      setDownloadingId(null);
    }
  };

  if (authLoading || adminLoading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }
  if (!isAdmin) return <Navigate to="/" replace />;

  return (
    <div className="container mx-auto max-w-6xl px-4 py-10">
      <Link to="/admin" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-4">
        <ArrowLeft className="h-4 w-4" /> Admin
      </Link>

      <header className="mb-6">
        <h1 className="font-display text-4xl font-semibold tracking-tight text-foreground">Worksheet Downloads</h1>
        <p className="mt-1 text-muted-foreground">All worksheets generated by users</p>
      </header>

      <div className="relative mb-4 max-w-md">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Filter by query…"
          className="pl-9"
        />
      </div>

      {loading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : filtered.length === 0 ? (
        <p className="py-12 text-center text-muted-foreground">
          {rows.length === 0 ? "No worksheets downloaded yet." : "No matches."}
        </p>
      ) : (
        <div className="rounded-xl border bg-card overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>User</TableHead>
                <TableHead>Query</TableHead>
                <TableHead>Date</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.map((row) => (
                <TableRow key={row.id}>
                  <TableCell className="font-medium">{row.display_name || "Anonymous"}</TableCell>
                  <TableCell className="text-muted-foreground">{truncate(row.query, 80)}</TableCell>
                  <TableCell className="text-muted-foreground whitespace-nowrap">{formatDate(row.created_at)}</TableCell>
                  <TableCell className="text-right">
                    {row.file_path ? (
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handleDownload(row)}
                        disabled={downloadingId === row.id}
                      >
                        {downloadingId === row.id ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          <><Download className="h-4 w-4 mr-1.5" /> Download PDF</>
                        )}
                      </Button>
                    ) : (
                      <span className="text-xs text-muted-foreground">No file</span>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  );
};

export default AdminWorksheets;
